Update hugo.yml

diff --git a/.github/workflows/hugo.yml b/.github/workflows/hugo.yml
--- a/.github/workflows/hugo.yml
+++ b/.github/workflows/hugo.yml
@@ -47,14 +47,12 @@ jobs:
           HUGO_ENVIRONMENT: production
           HUGO_ENV: production
         run: |
-          hugo \
-            --gc \
-            --minify \
-            --baseURL "${{ steps.pages.outputs.base_url }}/"
-      - name: List contents of the public directory
-        run: ls -alh ./public  # Debugging: Check if the public folder has content
-      - name: Upload artifact
-        uses: actions/upload-artifact@v4
+          set -e  # Stop on error and print output
+          hugo --gc --minify --baseURL "${{ steps.pages.outputs.base_url }}/"
+      - name: List contents of the public directory before upload
+        run: ls -alh ./public  # Debugging: Check if the public folder has content before upload
+      - name: Upload Pages artifact
+        uses: actions/upload-pages-artifact@v2
         with:
           path: ./public
 
